### ISSUE TITLE
SEGV : in rewirepath

### ISSUE THREAD

**Issue by bauom** [0x0584/Lem-in#6]
there is a segv when i try to run map "test_farm" it have a segv in the rewire funct line 390

**Comment by 0x0584** [comment]
I check that and fix it as soon as possible!

**Comment by 0x0584** [comment]
~~Couldn't reproduce the same behavior which caused the `segfault`~~

This is due a weird bug where the `walk_edge[i]` is set `NULL` somewhere! _Working on it right now_.
